package pe.org.camaracomercioica.protestos.util;
import org.springframework.web.multipart.MultipartFile; import pe.org.camaracomercioica.protestos.exception.BadRequestException; import java.io.*; import java.util.*; import java.util.zip.*;
public class UploadValidator {
 private final long maxBytes; public UploadValidator(long maxBytes){this.maxBytes=maxBytes;}
 public String validateDocument(MultipartFile f){basic(f,Set.of("pdf","png","jpg","jpeg"));byte[] b=bytes(f);String ext=extension(f);if("pdf".equals(ext)&&starts(b,"%PDF-"))return "application/pdf";if("png".equals(ext)&&prefix(b,new int[]{0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a}))return "image/png";if(("jpg".equals(ext)||"jpeg".equals(ext))&&prefix(b,new int[]{0xff,0xd8,0xff}))return "image/jpeg";throw new BadRequestException("La firma del archivo no coincide con su extensión");}
 public String validateExcel(MultipartFile f){basic(f,Set.of("xlsx","xls"));byte[] b=bytes(f);if("xls".equals(extension(f))&&prefix(b,new int[]{0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1}))return "application/vnd.ms-excel";if(!"xlsx".equals(extension(f)))throw new BadRequestException("La firma del archivo no coincide con su extensión");validateXlsxZip(b);return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";}
 private void basic(MultipartFile f,Set<String> exts){String n=f.getOriginalFilename();if(f.isEmpty()||n==null||n.contains("..")||n.contains("/")||n.contains("\\")||n.lastIndexOf('.')<1)throw new BadRequestException("Archivo inválido");if(f.getSize()>maxBytes||!exts.contains(extension(f)))throw new BadRequestException("Tipo o tamaño de archivo no permitido");} private String extension(MultipartFile f){String n=f.getOriginalFilename();return n.substring(n.lastIndexOf('.')+1).toLowerCase(Locale.ROOT);}
 private void validateXlsxZip(byte[] b){if(!prefix(b,new int[]{0x50,0x4b,0x03,0x04}))throw new BadRequestException("El XLSX no es un contenedor ZIP válido");long expanded=0;int entries=0;boolean contentTypes=false,workbook=false;try(var zin=new ZipInputStream(new ByteArrayInputStream(b))){ZipEntry e;byte[] buffer=new byte[8192];while((e=zin.getNextEntry())!=null){if(++entries>1000)throw new BadRequestException("El XLSX contiene demasiados archivos");String n=e.getName();contentTypes|="[Content_Types].xml".equals(n);workbook|="xl/workbook.xml".equals(n);int read;while((read=zin.read(buffer))>0){expanded+=read;if(expanded>maxBytes*20)throw new BadRequestException("El XLSX excede el límite expandido");}}}catch(IOException ex){throw new BadRequestException("XLSX corrupto");}if(!contentTypes||!workbook)throw new BadRequestException("Estructura XLSX inválida");}
 private byte[] bytes(MultipartFile f){try{return f.getBytes();}catch(IOException e){throw new BadRequestException("No se pudo leer el archivo");}} private boolean starts(byte[] b,String s){return prefix(b,s.getBytes(java.nio.charset.StandardCharsets.US_ASCII));} private boolean prefix(byte[] b,byte[] p){if(b.length<p.length)return false;for(int i=0;i<p.length;i++)if(b[i]!=p[i])return false;return true;} private boolean prefix(byte[] b,int[] p){if(b.length<p.length)return false;for(int i=0;i<p.length;i++)if((b[i]&255)!=p[i])return false;return true;}
}