spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

app.security.cookie.secure=true
app.security.cookie.same-site=Strict
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
app.storage.location=${STORAGE_LOCATION:/app/storage}
app.data.demo-enabled=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
