package pe.org.camaracomercioica.protestos.config;
import com.nimbusds.jose.jwk.source.ImmutableSecret; import org.springframework.beans.factory.annotation.Value; import org.springframework.context.annotation.*; import org.springframework.http.HttpMethod; import org.springframework.security.authentication.*; import org.springframework.security.authentication.dao.DaoAuthenticationProvider; import org.springframework.security.config.Customizer; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.core.*; import org.springframework.security.oauth2.jwt.*; import org.springframework.security.oauth2.server.resource.authentication.*; import org.springframework.security.web.SecurityFilterChain; import org.springframework.web.cors.*; import pe.org.camaracomercioica.protestos.security.*; import javax.crypto.spec.SecretKeySpec; import java.nio.charset.StandardCharsets; import java.util.*;
@Configuration @EnableMethodSecurity public class SecurityConfig {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder(12);}
 @Bean AuthenticationManager authenticationManager(DatabaseUserDetailsService uds,PasswordEncoder encoder){var provider=new DaoAuthenticationProvider(uds);provider.setPasswordEncoder(encoder);return new ProviderManager(provider);}
 @Bean JwtEncoder jwtEncoder(@Value("${app.security.jwt.secret}") String secret){return new NimbusJwtEncoder(new ImmutableSecret<>(key(secret)));}
 @Bean JwtDecoder jwtDecoder(@Value("${app.security.jwt.secret}") String secret,@Value("${app.security.jwt.issuer}") String issuer){var decoder=NimbusJwtDecoder.withSecretKey(key(secret)).macAlgorithm(org.springframework.security.oauth2.jose.jws.MacAlgorithm.HS256).build();OAuth2TokenValidator<Jwt> validator=new DelegatingOAuth2TokenValidator<>(JwtValidators.createDefault(),new JwtIssuerValidator(issuer));decoder.setJwtValidator(validator);return decoder;}
 private SecretKeySpec key(String secret){return new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256");}
 @Bean JwtAuthenticationConverter jwtAuthenticationConverter(){var authorities=new JwtGrantedAuthoritiesConverter();authorities.setAuthoritiesClaimName("roles");authorities.setAuthorityPrefix("ROLE_");var converter=new JwtAuthenticationConverter();converter.setJwtGrantedAuthoritiesConverter(authorities);return converter;}
 @Bean SecurityFilterChain chain(HttpSecurity http,JwtAuthenticationConverter converter,SecurityErrorHandler errors)throws Exception{return http.csrf(csrf->csrf.disable()).cors(Customizer.withDefaults()).headers(h->h.frameOptions(f->f.deny()).contentTypeOptions(Customizer.withDefaults())).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).exceptionHandling(e->e.authenticationEntryPoint(errors).accessDeniedHandler(errors)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/login","/actuator/health","/v3/api-docs/**","/swagger-ui/**").permitAll().requestMatchers(HttpMethod.GET,"/api/entidades").authenticated().requestMatchers(HttpMethod.GET,"/api/solicitudes").hasAnyRole("ADMIN","ANALISTA").requestMatchers("/api/reportes/**","/api/excel/**").hasAnyRole("ADMIN","ANALISTA").requestMatchers("/api/entidades/**","/api/analistas/**","/api/auditoria/**").hasRole("ADMIN").requestMatchers("/api/solicitudes/*/estado").hasAnyRole("ADMIN","ANALISTA").anyRequest().authenticated()).oauth2ResourceServer(o->o.authenticationEntryPoint(errors).accessDeniedHandler(errors).jwt(j->j.jwtAuthenticationConverter(converter))).build();}
 @Bean CorsConfigurationSource cors(@Value("${app.cors.allowed-origin}") String origin){var c=new CorsConfiguration();c.setAllowedOrigins(List.of(origin));c.setAllowedMethods(List.of("GET","POST","PUT","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Authorization","Content-Type"));c.setExposedHeaders(List.of("Location"));c.setAllowCredentials(true);var source=new UrlBasedCorsConfigurationSource();source.registerCorsConfiguration("/**",c);return source;}
}
