package pe.org.camaracomercioica.protestos;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.mock.web.MockMultipartFile; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.test.context.support.WithMockUser; import org.springframework.test.web.servlet.MockMvc; import pe.org.camaracomercioica.protestos.model.*; import pe.org.camaracomercioica.protestos.repository.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class SecurityIntegrationTest {
 @Autowired MockMvc mvc; @Autowired RolRepository roles; @Autowired UsuarioRepository users; @Autowired PasswordEncoder encoder;
 @BeforeEach void seed(){if(users.findByEmailIgnoreCase("login@test.local").isEmpty()){var role=roles.findByNombre("ADMIN").orElseGet(()->{var r=new Rol();r.setNombre("ADMIN");return roles.save(r);});var u=new Usuario();u.setNombreCompleto("Login Test");u.setEmail("login@test.local");u.setPasswordHash(encoder.encode("Password1!"));u.setRol(role);users.save(u);}}
 @Test void error401UsaContratoApiError() throws Exception {mvc.perform(get("/api/solicitudes")).andExpect(status().isUnauthorized()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andExpect(jsonPath("$.code").value("UNAUTHORIZED")).andExpect(jsonPath("$.path").value("/api/solicitudes"));}
 @Test void loginExitosoDevuelveJwt() throws Exception {mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"login@test.local\",\"password\":\"Password1!\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.accessToken").isNotEmpty()).andExpect(jsonPath("$.usuario.roles[0]").value("ADMIN"));}
 @Test @WithMockUser(roles="ENTIDAD") void entidadNoListaTodasLasSolicitudes() throws Exception {mvc.perform(get("/api/solicitudes")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("FORBIDDEN"));}
 @Test @WithMockUser(roles="ENTIDAD") void entidadNoAccedeReportes() throws Exception {mvc.perform(get("/api/reportes/solicitudes")).andExpect(status().isForbidden());}
 @Test @WithMockUser(roles="ENTIDAD") void entidadAutenticadaPuedeListarEntidades() throws Exception {mvc.perform(get("/api/entidades")).andExpect(status().isOk()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON));}
 @Test @WithMockUser(roles="ENTIDAD") void entidadNoPuedeCrearEntidades() throws Exception {mvc.perform(post("/api/entidades").with(csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"ruc\":\"20999999999\",\"razonSocial\":\"Entidad Test\",\"email\":\"contacto@test.local\"}")).andExpect(status().isForbidden()).andExpect(jsonPath("$.code").value("FORBIDDEN"));}
 @Test @WithMockUser(roles="ENTIDAD") void entidadNoCargaExcel() throws Exception {var f=new MockMultipartFile("file","carga.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",new byte[]{1});mvc.perform(multipart("/api/excel/upload").file(f).with(csrf())).andExpect(status().isForbidden());}
 @Test @WithMockUser(username="login@test.local",roles="ANALISTA") void analistaPuedeCargarExcel() throws Exception {var f=new MockMultipartFile("file","carga.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",new byte[]{1});mvc.perform(multipart("/api/excel/upload").file(f).with(csrf())).andExpect(status().isCreated()).andExpect(jsonPath("$.estado").value("RECIBIDA"));}
 @Test void validaPayloadLogin() throws Exception {mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"mal\",\"password\":\"1\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));}
}
