CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(30) NOT NULL,
    CONSTRAINT uk_roles_nombre UNIQUE (nombre)
);

CREATE TABLE entidades_financieras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    contacto varchar(150),
    creado_en timestamp(6) with time zone NOT NULL,
    email varchar(150),
    razon_social varchar(150) NOT NULL,
    ruc varchar(11) NOT NULL,
    CONSTRAINT uk_entidades_ruc UNIQUE (ruc)
);

CREATE TABLE deudores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actualizado_en timestamp(6) with time zone NOT NULL,
    creado_en timestamp(6) with time zone NOT NULL,
    email varchar(150),
    nombre_razon_social varchar(180) NOT NULL,
    numero_documento varchar(20) NOT NULL,
    telefono varchar(30),
    tipo_documento varchar(10) NOT NULL,
    tipo_persona varchar(20) NOT NULL,
    CONSTRAINT uk_deudores_documento UNIQUE (tipo_documento, numero_documento),
    CONSTRAINT ck_deudores_tipo_documento CHECK (tipo_documento IN ('DNI', 'RUC', 'CE')),
    CONSTRAINT ck_deudores_tipo_persona CHECK (tipo_persona IN ('NATURAL', 'JURIDICA'))
);

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    creado_en timestamp(6) with time zone NOT NULL,
    email varchar(150) NOT NULL,
    nombre_completo varchar(150) NOT NULL,
    password_hash varchar(100) NOT NULL,
    deudor_id bigint,
    entidad_id bigint,
    rol_id bigint NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_deudor UNIQUE (deudor_id),
    CONSTRAINT fk_usuarios_deudor FOREIGN KEY (deudor_id) REFERENCES deudores(id),
    CONSTRAINT fk_usuarios_entidad FOREIGN KEY (entidad_id) REFERENCES entidades_financieras(id),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles(id)
);

CREATE TABLE analistas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL,
    disponible boolean NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT uk_analistas_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_analistas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE cargas_excel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checksum_sha256 varchar(64),
    creado_en timestamp(6) with time zone NOT NULL,
    estado varchar(30) NOT NULL,
    filas_con_error integer NOT NULL,
    filas_importadas integer NOT NULL,
    mime_type varchar(100),
    nombre_archivo varchar(255) NOT NULL,
    resumen varchar(500),
    size_bytes bigint,
    storage_key varchar(255) NOT NULL,
    total_filas integer NOT NULL,
    entidad_id bigint,
    usuario_id bigint NOT NULL,
    CONSTRAINT ck_cargas_excel_estado CHECK (estado IN ('RECIBIDA', 'PROCESADA', 'CON_ERROR')),
    CONSTRAINT fk_cargas_excel_entidad FOREIGN KEY (entidad_id) REFERENCES entidades_financieras(id),
    CONSTRAINT fk_cargas_excel_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE protestos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actualizado_en timestamp(6) with time zone NOT NULL,
    creado_en timestamp(6) with time zone NOT NULL,
    estado varchar(30) NOT NULL,
    fecha_protesto date NOT NULL,
    fecha_vencimiento date,
    moneda varchar(3) NOT NULL,
    monto numeric(14,2) NOT NULL,
    numero_titulo varchar(50),
    tipo_titulo varchar(50) NOT NULL,
    deudor_id bigint NOT NULL,
    entidad_id bigint NOT NULL,
    origen_carga_id bigint,
    CONSTRAINT ck_protestos_estado CHECK (estado IN ('VIGENTE', 'REGULARIZADO', 'RECTIFICADO', 'ANULADO')),
    CONSTRAINT fk_protestos_deudor FOREIGN KEY (deudor_id) REFERENCES deudores(id),
    CONSTRAINT fk_protestos_entidad FOREIGN KEY (entidad_id) REFERENCES entidades_financieras(id),
    CONSTRAINT fk_protestos_carga FOREIGN KEY (origen_carga_id) REFERENCES cargas_excel(id)
);

CREATE TABLE carga_excel_filas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detalle_error varchar(500),
    estado varchar(20) NOT NULL,
    fecha_protesto date NOT NULL,
    moneda varchar(3) NOT NULL,
    monto numeric(14,2) NOT NULL,
    nombre_deudor varchar(180) NOT NULL,
    numero_documento varchar(20) NOT NULL,
    numero_fila integer NOT NULL,
    carga_id bigint NOT NULL,
    protesto_id bigint,
    CONSTRAINT ck_carga_filas_estado CHECK (estado IN ('VALIDA', 'IMPORTADA', 'OBSERVADA', 'ERROR')),
    CONSTRAINT fk_carga_filas_carga FOREIGN KEY (carga_id) REFERENCES cargas_excel(id),
    CONSTRAINT fk_carga_filas_protesto FOREIGN KEY (protesto_id) REFERENCES protestos(id)
);

CREATE TABLE solicitudes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actualizado_en timestamp(6) with time zone NOT NULL,
    codigo varchar(30) NOT NULL,
    creado_en timestamp(6) with time zone NOT NULL,
    estado varchar(30) NOT NULL,
    moneda varchar(3) NOT NULL,
    monto numeric(14,2) NOT NULL,
    motivo varchar(1000) NOT NULL,
    observacion varchar(1000),
    tipo_tramite varchar(30) NOT NULL,
    version bigint NOT NULL,
    analista_id bigint,
    deudor_id bigint NOT NULL,
    entidad_id bigint NOT NULL,
    solicitante_id bigint NOT NULL,
    CONSTRAINT uk_solicitudes_codigo UNIQUE (codigo),
    CONSTRAINT ck_solicitudes_estado CHECK (estado IN (
        'REGISTRADA', 'EN_REVISION_CCI', 'OBSERVADA_CCI', 'DERIVADA_ENTIDAD',
        'EN_REVISION_ANALISTA', 'OBSERVADA_ENTIDAD', 'RECHAZADA',
        'APROBADA_ENTIDAD', 'FINALIZADA', 'LEVANTAMIENTO_PROCESADO'
    )),
    CONSTRAINT ck_solicitudes_tipo CHECK (tipo_tramite IN ('REGISTRO_PROTESTO', 'REGULARIZACION', 'RECTIFICACION')),
    CONSTRAINT fk_solicitudes_analista FOREIGN KEY (analista_id) REFERENCES analistas(id),
    CONSTRAINT fk_solicitudes_deudor FOREIGN KEY (deudor_id) REFERENCES deudores(id),
    CONSTRAINT fk_solicitudes_entidad FOREIGN KEY (entidad_id) REFERENCES entidades_financieras(id),
    CONSTRAINT fk_solicitudes_solicitante FOREIGN KEY (solicitante_id) REFERENCES usuarios(id)
);

CREATE TABLE solicitud_protestos (
    solicitud_id bigint NOT NULL,
    protesto_id bigint NOT NULL,
    PRIMARY KEY (solicitud_id, protesto_id),
    CONSTRAINT fk_solicitud_protestos_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id),
    CONSTRAINT fk_solicitud_protestos_protesto FOREIGN KEY (protesto_id) REFERENCES protestos(id)
);

CREATE TABLE documentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checksum_sha256 varchar(64),
    creado_en timestamp(6) with time zone NOT NULL,
    mime_type varchar(100) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key varchar(255) NOT NULL,
    solicitud_id bigint NOT NULL,
    CONSTRAINT fk_documentos_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id)
);

CREATE TABLE documentos_tramite (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo boolean NOT NULL,
    checksum_sha256 varchar(64),
    creado_en timestamp(6) with time zone NOT NULL,
    descripcion varchar(500),
    mime_type varchar(100) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    orden integer NOT NULL,
    size_bytes bigint NOT NULL,
    storage_key varchar(255) NOT NULL,
    titulo varchar(120) NOT NULL,
    tipo varchar(30) DEFAULT 'FORMATO_REQUERIDO' NOT NULL
);

CREATE TABLE solicitud_eventos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_rol varchar(30) NOT NULL,
    comentario varchar(1000),
    creado_en timestamp(6) with time zone NOT NULL,
    estado_anterior varchar(30),
    estado_nuevo varchar(30) NOT NULL,
    actor_id bigint NOT NULL,
    solicitud_id bigint NOT NULL,
    CONSTRAINT ck_eventos_estado_anterior CHECK (estado_anterior IS NULL OR estado_anterior IN (
        'REGISTRADA', 'EN_REVISION_CCI', 'OBSERVADA_CCI', 'DERIVADA_ENTIDAD',
        'EN_REVISION_ANALISTA', 'OBSERVADA_ENTIDAD', 'RECHAZADA',
        'APROBADA_ENTIDAD', 'FINALIZADA', 'LEVANTAMIENTO_PROCESADO'
    )),
    CONSTRAINT ck_eventos_estado_nuevo CHECK (estado_nuevo IN (
        'REGISTRADA', 'EN_REVISION_CCI', 'OBSERVADA_CCI', 'DERIVADA_ENTIDAD',
        'EN_REVISION_ANALISTA', 'OBSERVADA_ENTIDAD', 'RECHAZADA',
        'APROBADA_ENTIDAD', 'FINALIZADA', 'LEVANTAMIENTO_PROCESADO'
    )),
    CONSTRAINT fk_eventos_actor FOREIGN KEY (actor_id) REFERENCES usuarios(id),
    CONSTRAINT fk_eventos_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id)
);

CREATE TABLE auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accion varchar(80) NOT NULL,
    actor varchar(150) NOT NULL,
    detalle varchar(500),
    fecha timestamp(6) with time zone NOT NULL,
    recurso varchar(80) NOT NULL,
    recurso_id varchar(80)
);

CREATE INDEX idx_cargas_excel_entidad ON cargas_excel(entidad_id);
CREATE INDEX idx_cargas_excel_usuario ON cargas_excel(usuario_id);
CREATE INDEX idx_cargas_excel_estado ON cargas_excel(estado);
CREATE INDEX idx_carga_filas_carga ON carga_excel_filas(carga_id);
CREATE INDEX idx_carga_filas_estado ON carga_excel_filas(estado);
CREATE INDEX idx_deudores_documento ON deudores(numero_documento);
CREATE INDEX idx_deudores_nombre ON deudores(nombre_razon_social);
CREATE INDEX idx_documentos_solicitud ON documentos(solicitud_id);
CREATE INDEX idx_documentos_tramite_activo ON documentos_tramite(activo);
CREATE INDEX idx_documentos_tramite_orden ON documentos_tramite(orden);
CREATE INDEX idx_protestos_deudor ON protestos(deudor_id);
CREATE INDEX idx_protestos_entidad ON protestos(entidad_id);
CREATE INDEX idx_protestos_estado ON protestos(estado);
CREATE INDEX idx_protestos_fecha ON protestos(fecha_protesto);
CREATE INDEX idx_solicitudes_estado ON solicitudes(estado);
CREATE INDEX idx_solicitudes_entidad ON solicitudes(entidad_id);
CREATE INDEX idx_solicitudes_deudor ON solicitudes(deudor_id);
CREATE INDEX idx_solicitudes_creado ON solicitudes(creado_en);
CREATE INDEX idx_solicitud_eventos_solicitud ON solicitud_eventos(solicitud_id);
CREATE INDEX idx_solicitud_eventos_fecha ON solicitud_eventos(creado_en);
