ALTER TABLE usuarios
    ADD COLUMN activado_en timestamp(6) with time zone;

UPDATE usuarios
SET activado_en = creado_en;

CREATE TABLE invitaciones_analista (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analista_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    expira_en timestamp(6) with time zone NOT NULL,
    usado_en timestamp(6) with time zone,
    revocado_en timestamp(6) with time zone,
    creado_en timestamp(6) with time zone NOT NULL,
    creado_por varchar(150) NOT NULL,
    CONSTRAINT uk_invitaciones_analista_token UNIQUE (token_hash),
    CONSTRAINT fk_invitaciones_analista_analista FOREIGN KEY (analista_id) REFERENCES analistas(id),
    CONSTRAINT ck_invitaciones_analista_expiracion CHECK (expira_en > creado_en),
    CONSTRAINT ck_invitaciones_analista_finalizacion CHECK (usado_en IS NULL OR revocado_en IS NULL)
);

CREATE INDEX idx_invitaciones_analista_analista ON invitaciones_analista (analista_id);
CREATE INDEX idx_invitaciones_analista_expira ON invitaciones_analista (expira_en);
